"""SPEC §13: a row-level trace of one seeded book, for inspection and debugging.

**This is a trace of what happened, not a recommendation list.** It records what each
strategy did with each simulated mandate. It carries no advice column and must never
acquire one: what a merchant *should* do generalises across books and belongs in a
decision table, and putting it beside a synthetic id invites someone to act on a customer
who does not exist.

Single seed, structurally. `build_trace` generates one book and calls `run_paired`; there
is no code path that merges seeds, because a mandate id is only meaningful within the seed
that produced it and a merged export would imply otherwise.
"""

from __future__ import annotations

import csv
import io
from datetime import UTC, datetime
from enum import StrEnum

from pydantic import ConfigDict, Field

from rebound.compliance.guard import ComplianceBlock, ComplianceReschedule
from rebound.config import Assumptions, load_assumptions
from rebound.domain.entities import (
    Bank,
    Customer,
    DomainModel,
    EpisodeOutcome,
    Mandate,
    RecoveryEpisode,
)
from rebound.harness.runner import HarnessReport, default_strategies, run_paired
from rebound.population.book import Book, generate_book

PAISE_PER_RUPEE = 100
SIM_PREFIX = "SIM-"

# Printed at the head of every export, in both formats. A row separated from its header is
# still traceable because the seed and hash repeat on every row; this sentence exists so
# that a reader who never sees a row in isolation cannot mistake the file for real data.
SYNTHETIC_NOTICE = (
    "These mandates are SYNTHETIC. They were generated by the seed below and exist only "
    "in this run; they do not correspond to any real customer, and re-running with a "
    "different seed produces a different population. This file is a trace of what the "
    "simulation did, not a list of accounts to act on."
)


class GuardVerdict(StrEnum):
    """What the compliance guard did with the proposal behind a row."""

    # Opening debits are the merchant's scheduled charge, not a proposed retry, so the
    # guard is never consulted. Recorded explicitly rather than left blank, so that a
    # missing verdict always means a defect rather than "not applicable".
    NOT_REVIEWED = "not_reviewed_opening_debit"
    ALLOWED = "allowed"
    RESCHEDULED = "rescheduled"
    BLOCKED = "blocked"


def sim_id(mandate_id: str) -> str:
    """`mandate-000247` -> `SIM-000247`. Derived, never stored on the domain object.

    The prefix is not decoration. Every id that leaves this system carries it so that a
    row pasted into a ticket, a spreadsheet or a query cannot be mistaken for a production
    identifier.
    """
    return f"{SIM_PREFIX}{mandate_id.rsplit('-', 1)[-1]}"


class TraceHeader(DomainModel):
    model_config = ConfigDict(frozen=True, extra="forbid")

    seed: int
    output_hash: str = Field(min_length=1)
    # The configuration this trace was generated under. Recorded so a file can be checked
    # against the run it is supposed to explain: the same seed yields the same mandate ids
    # whatever the config, so a trace of the wrong population is invisible without this.
    config_fingerprint: str = Field(min_length=1)
    # The only non-deterministic field in the export, and it is provenance rather than
    # result: it never enters the output hash and nothing reconciles against it.
    exported_at: datetime
    strategies: tuple[str, ...] = Field(min_length=1)
    months: int = Field(gt=0)
    book_size: int = Field(gt=0)
    notice: str = SYNTHETIC_NOTICE


class TraceAttempt(DomainModel):
    """One attempt, or one proposal the guard refused. Long format: everything needed to
    filter without a join back to the mandate table."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    sim_id: str = Field(min_length=1)
    seed: int
    output_hash: str = Field(min_length=1)
    strategy: str = Field(min_length=1)
    cycle_index: int = Field(ge=0)
    # None for a proposal that was blocked: it never became an attempt, and numbering it
    # would imply the merchant made one.
    attempt_number: int | None = None
    is_retry: bool
    scheduled_at: datetime
    executed_at: datetime | None = None
    guard_verdict: GuardVerdict
    # Set only when the guard moved the retry, so a reader can see both times.
    rescheduled_from: datetime | None = None
    rescheduled_to: datetime | None = None
    # Set only when the guard refused it.
    blocked_by_rule: str | None = None
    blocked_detail: str | None = None
    outcome: str | None = None
    reason_code: str | None = None
    amount_inr: float = Field(ge=0.0)


class TraceMandate(DomainModel):
    """Generated attributes, keyed on `sim_id`. A second table rather than columns
    repeated on every attempt row."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    sim_id: str = Field(min_length=1)
    seed: int
    output_hash: str = Field(min_length=1)
    rail: str
    mandate_cap_inr: float
    ticket_inr: float
    bank_id: str
    bank_name: str
    income_band: str
    salary_credit_day: int
    billing_day: int
    intent_score: float


class TraceOutcome(DomainModel):
    """What each strategy ended up with on this mandate, side by side."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    sim_id: str = Field(min_length=1)
    strategy: str = Field(min_length=1)
    episodes: int = Field(ge=0)
    recovered_episodes: int = Field(ge=0)
    lapsed_episodes: int = Field(ge=0)
    recovered_inr: float = Field(ge=0.0)
    median_days_to_recovery: int | None = None


class Trace(DomainModel):
    model_config = ConfigDict(frozen=True, extra="forbid")

    header: TraceHeader
    mandates: tuple[TraceMandate, ...]
    attempts: tuple[TraceAttempt, ...]
    outcomes: tuple[TraceOutcome, ...]

    def recovered_inr(self, strategy: str) -> float:
        return sum(o.recovered_inr for o in self.outcomes if o.strategy == strategy)


class TraceCollector:
    """A `RunObserver` that keeps the full per-mandate detail a trace needs.

    Unlike `SegmentCollector` this retains whole episodes and guard verdicts, which is only
    affordable because a trace is one seed of one book by construction.
    """

    def __init__(self) -> None:
        self.mandates: dict[str, Mandate] = {}
        self.episodes: dict[tuple[str, str], list[RecoveryEpisode]] = {}
        self.blocks: dict[tuple[str, str, int], tuple[ComplianceBlock, ...]] = {}
        self.reschedules: dict[tuple[str, str, int], tuple[ComplianceReschedule, ...]] = {}

    def saw_mandate(self, strategy: str, seed: int, mandate: Mandate) -> None:
        self.mandates.setdefault(mandate.id, mandate)

    def saw_episode(
        self, strategy: str, seed: int, mandate: Mandate, episode: RecoveryEpisode
    ) -> None:
        self.episodes.setdefault((strategy, mandate.id), []).append(episode)

    def saw_opening_attempt(self, *_: object) -> None:
        """Not needed here. The trace is built from episodes and their attempts; an
        opening that succeeded starts no episode and so has no rows to carry."""

    def saw_cycle_guard_events(
        self,
        strategy: str,
        seed: int,
        mandate: Mandate,
        cycle_index: int,
        blocks: tuple[ComplianceBlock, ...],
        reschedules: tuple[ComplianceReschedule, ...],
    ) -> None:
        key = (strategy, mandate.id, cycle_index)
        self.blocks[key] = blocks
        self.reschedules[key] = reschedules


def _verdict_for(
    attempt_time: datetime, reschedules: tuple[ComplianceReschedule, ...]
) -> ComplianceReschedule | None:
    """The reschedule that produced this attempt's time, if any.

    Matched on the *destination* time, because that is what the attempt was executed at.
    Within one cycle a strategy proposes at most a handful of times and each lands
    distinctly, so this is unambiguous — and `test_every_reschedule_appears_in_the_trace`
    fails loudly if it ever stops being.
    """
    for entry in reschedules:
        if entry.rescheduled_at == attempt_time:
            return entry
    return None


def _attempt_rows(
    collector: TraceCollector,
    strategy: str,
    mandate: Mandate,
    seed: int,
    output_hash: str,
) -> list[TraceAttempt]:
    rows: list[TraceAttempt] = []
    for episode in collector.episodes.get((strategy, mandate.id), []):
        key = (strategy, mandate.id, episode.cycle_index)
        reschedules = collector.reschedules.get(key, ())
        for attempt in episode.attempts:
            moved = _verdict_for(attempt.scheduled_at, reschedules) if attempt.is_retry else None
            rows.append(
                TraceAttempt(
                    sim_id=sim_id(mandate.id),
                    seed=seed,
                    output_hash=output_hash,
                    strategy=strategy,
                    cycle_index=episode.cycle_index,
                    attempt_number=attempt.attempt_number,
                    is_retry=attempt.is_retry,
                    scheduled_at=attempt.scheduled_at,
                    executed_at=attempt.executed_at,
                    guard_verdict=(
                        GuardVerdict.NOT_REVIEWED
                        if not attempt.is_retry
                        else GuardVerdict.RESCHEDULED
                        if moved
                        else GuardVerdict.ALLOWED
                    ),
                    rescheduled_from=moved.proposed_at if moved else None,
                    rescheduled_to=moved.rescheduled_at if moved else None,
                    outcome=attempt.outcome.value,
                    reason_code=attempt.reason_code.value if attempt.reason_code else None,
                    amount_inr=attempt.amount_paise / PAISE_PER_RUPEE,
                )
            )
        # Proposals the guard refused. They never became attempts, so they carry no
        # attempt number and no outcome — but they are the whole point of a compliance
        # trace and omitting them would make the guard invisible.
        for block in collector.blocks.get(key, ()):
            rows.append(
                TraceAttempt(
                    sim_id=sim_id(mandate.id),
                    seed=seed,
                    output_hash=output_hash,
                    strategy=strategy,
                    cycle_index=episode.cycle_index,
                    attempt_number=None,
                    is_retry=True,
                    scheduled_at=block.scheduled_at,
                    guard_verdict=GuardVerdict.BLOCKED,
                    blocked_by_rule=block.rule,
                    blocked_detail=block.detail,
                    amount_inr=episode.original_attempt.amount_paise / PAISE_PER_RUPEE,
                )
            )
    return rows


def _median(values: list[int]) -> int | None:
    if not values:
        return None
    ordered = sorted(values)
    return ordered[len(ordered) // 2]


def _outcome_rows(collector: TraceCollector, strategy: str, mandate: Mandate) -> TraceOutcome:
    episodes = collector.episodes.get((strategy, mandate.id), [])
    recovered = [e for e in episodes if e.outcome is EpisodeOutcome.RECOVERED]
    return TraceOutcome(
        sim_id=sim_id(mandate.id),
        strategy=strategy,
        episodes=len(episodes),
        recovered_episodes=len(recovered),
        lapsed_episodes=len(episodes) - len(recovered),
        recovered_inr=sum(e.amount_recovered_paise for e in recovered) / PAISE_PER_RUPEE,
        median_days_to_recovery=_median([e.days_to_recovery or 0 for e in recovered]),
    )


def _mandate_row(
    mandate: Mandate, customer: Customer, bank: Bank, book: Book, seed: int, output_hash: str
) -> TraceMandate:
    return TraceMandate(
        sim_id=sim_id(mandate.id),
        seed=seed,
        output_hash=output_hash,
        rail=mandate.rail.value,
        mandate_cap_inr=mandate.max_amount_paise / PAISE_PER_RUPEE,
        # What is actually debited, which is not the drawn ticket: SPEC §11 records that
        # the harness debits min(avg_ticket, cap), so this is constant across the book in
        # the current population model. Reported as debited rather than as drawn, because
        # a trace should show what happened.
        ticket_inr=min(book.merchant.avg_ticket_paise, mandate.max_amount_paise)
        / PAISE_PER_RUPEE,
        bank_id=bank.id,
        bank_name=bank.name,
        income_band=customer.income_band.value,
        salary_credit_day=customer.salary_credit_day,
        billing_day=mandate.created_at.day,
        intent_score=customer.intent_score,
    )


class MultipleSeedsError(ValueError):
    """SPEC §13.1. A trace spans exactly one seed."""


def build_trace(
    seed: int, assumptions: Assumptions | None = None, book_size: int | None = None
) -> Trace:
    """One seed, one book, every strategy side by side.

    Takes a single `int`, not a sequence. That is the enforcement: there is no argument
    shape that could express a multi-seed trace, so the constraint cannot be violated by
    passing a longer list. `run_paired` is used rather than `run_experiment` for the same
    reason — the latter loops over seeds.
    """
    if not isinstance(seed, int) or isinstance(seed, bool):
        raise MultipleSeedsError(
            f"a trace covers exactly one seed; got {type(seed).__name__}. A mandate id "
            "means nothing across seeds, so a merged export would imply a continuity that "
            "does not exist."
        )
    assumptions = assumptions or load_assumptions()
    if book_size is not None:
        assumptions = assumptions.with_values({"book.size": book_size})
    book = generate_book(assumptions, seed)
    strategies = default_strategies(assumptions)
    collector = TraceCollector()
    report = run_paired(book, strategies, seed, assumptions, observer=collector)
    return _assemble(collector, book, report, seed, assumptions.fingerprint())


def _assemble(
    collector: TraceCollector,
    book: Book,
    report: HarnessReport,
    seed: int,
    fingerprint: str,
) -> Trace:
    customers = {c.id: c for c in book.customers}
    banks = {b.id: b for b in book.banks}
    names = list(report.strategies)
    output_hash = report.output_hash
    mandates = [
        _mandate_row(
            m, customers[m.customer_id], banks[customers[m.customer_id].bank_id],
            book, seed, output_hash,
        )
        for m in book.mandates
    ]
    attempts = [
        row
        for name in names
        for m in book.mandates
        for row in _attempt_rows(collector, name, m, seed, output_hash)
    ]
    outcomes = [
        _outcome_rows(collector, name, m) for name in names for m in book.mandates
    ]
    return Trace(
        header=TraceHeader(
            seed=seed,
            output_hash=output_hash,
            config_fingerprint=fingerprint,
            exported_at=datetime.now(UTC),
            strategies=tuple(names),
            months=book.months,
            book_size=len(book.mandates),
        ),
        mandates=tuple(mandates),
        attempts=tuple(attempts),
        outcomes=tuple(outcomes),
    )


class Table(StrEnum):
    """Which CSV. Two files, joined on `sim_id`, rather than mandate attributes repeated
    on every attempt row."""

    ATTEMPTS = "attempts"
    MANDATES = "mandates"
    OUTCOMES = "outcomes"


def _header_lines(header: TraceHeader, table: Table) -> list[str]:
    """SPEC §13.2: on every export, in both formats. Comment lines, so the file still
    parses as CSV with `comment='#'` and is unmissable to a human opening it."""
    return [
        f"# rebound trace - {table.value}",
        f"# seed: {header.seed}",
        f"# output_hash: {header.output_hash}",
        f"# config_fingerprint: {header.config_fingerprint}",
        f"# exported_at: {header.exported_at.isoformat()}",
        f"# strategies: {', '.join(header.strategies)}",
        f"# book_size: {header.book_size} mandates over {header.months} months",
        "#",
        *[f"# {line}" for line in _wrap_notice(header.notice, 92)],
        "#",
    ]


def _wrap_notice(text: str, width: int) -> list[str]:
    lines, current = [], ""
    for word in text.split():
        if len(current) + len(word) + 1 > width and current:
            lines.append(current)
            current = ""
        current += ("" if not current else " ") + word
    return [*lines, current] if current else lines


def to_csv(trace: Trace, table: Table = Table.ATTEMPTS) -> str:
    """Long format. One row per attempt (or refused proposal); mandate attributes live in
    their own table so they are not repeated on every row."""
    rows: list[DomainModel]
    if table is Table.ATTEMPTS:
        rows = list(trace.attempts)
    elif table is Table.MANDATES:
        rows = list(trace.mandates)
    else:
        rows = list(trace.outcomes)
    buffer = io.StringIO()
    for line in _header_lines(trace.header, table):
        buffer.write(line + "\n")
    if not rows:
        return buffer.getvalue()
    fields = list(type(rows[0]).model_fields)
    writer = csv.DictWriter(buffer, fieldnames=fields, lineterminator="\n")
    writer.writeheader()
    for row in rows:
        writer.writerow(
            {k: _cell(v) for k, v in row.model_dump(mode="json").items()}
        )
    return buffer.getvalue()


def _cell(value: object) -> str:
    """Empty string for a missing value, never the word 'None'. A CSV read back into a
    dataframe should see a null, not a string."""
    return "" if value is None else str(value)
