"""SPEC §14.2: the observed failure a merchant sends, in two tiers.

The tier split is not a convenience. It is the honest statement of what each strategy
reads: `FixedSchedule` and `ReasonAware` need the failure itself, `BankAware` needs
somewhere to tally bank outcomes, and nothing here can serve a strategy whose inputs the
merchant has not supplied (SPEC §14.3).

This module is the single definition of the tiers. The CSV template of §14.9 derives its
columns from `MINIMUM_COLUMNS` and `EXTENDED_COLUMNS` rather than restating them, so the
two cannot drift apart.
"""

from __future__ import annotations

from datetime import time
from enum import StrEnum

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, model_validator

from rebound.domain.entities import AttemptOutcome, Paise, Rail
from rebound.domain.reason_codes import ReasonCode

# Rails cleared in a batch, which is the only case where the guard reads a bank field.
# Mirrors compliance.rules.BATCH_CLEARED_RAILS; kept as its own name so that importing it
# here cannot be mistaken for this module having a say in which rails those are.
_BATCH_CLEARED = (Rail.ENACH,)


class Tier(StrEnum):
    MINIMUM = "minimum"
    EXTENDED = "extended"


class AttemptRecord(BaseModel):
    """One attempt the merchant has itemised, with the outcome they observed."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    scheduled_at: AwareDatetime
    amount_paise: Paise = Field(gt=0)
    outcome: AttemptOutcome
    reason_code: ReasonCode | None = None
    attempt_number: int = Field(ge=1)

    @model_validator(mode="after")
    def outcome_and_reason_code_agree(self) -> AttemptRecord:
        # The same rule the domain model enforces (SPEC §0.4). Checked here too so a bad
        # CSV row is refused at the edge, named, rather than surfacing as a domain error.
        if self.outcome is AttemptOutcome.FAILURE and self.reason_code is None:
            raise ValueError("a FAILURE must carry a reason code")
        if self.outcome is AttemptOutcome.SUCCESS and self.reason_code is not None:
            raise ValueError("a SUCCESS must not carry a reason code")
        return self


class ObservedFailure(BaseModel):
    """One real failure, as the merchant observed it. Never generated by us."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    mandate_ref: str = Field(min_length=1)
    rail: Rail
    reason_code: ReasonCode
    failed_at: AwareDatetime
    amount_paise: Paise = Field(gt=0)
    mandate_cap_paise: Paise = Field(gt=0)
    attempt_number: int = Field(ge=1)
    # SPEC §14.2: required, never defaulted. Under the shipped inheritance reading the
    # guard blocks a retry with no valid notice on the original charge, and inventing a
    # notice time here would launder an un-notified debit into a compliant-looking retry.
    notified_at: AwareDatetime
    # Failed cycles in the preceding 12 months, excluding this one. The horizon is part
    # of the definition because SPEC §12's frequency bands are over a 12-month run.
    prior_failure_count: int = Field(ge=0)
    original_attempt_at: AwareDatetime | None = None
    bank_batch_cutoff_time: time | None = None

    # --- extended set ---------------------------------------------------------------
    bank_id: str | None = Field(default=None, min_length=1)
    # None means "not supplied"; an empty tuple would mean "there were none", which for a
    # failure that has already happened is a different and impossible claim.
    attempt_history: tuple[AttemptRecord, ...] | None = None

    @model_validator(mode="after")
    def a_retry_knows_when_the_original_ran(self) -> ObservedFailure:
        if self.attempt_number > 1 and self.original_attempt_at is None:
            raise ValueError(
                "original_attempt_at is required when attempt_number > 1: every strategy "
                "schedules from the original attempt, not from the last one"
            )
        return self

    @model_validator(mode="after")
    def batch_cleared_rails_need_a_cutoff(self) -> ObservedFailure:
        if self.rail in _BATCH_CLEARED and self.bank_batch_cutoff_time is None:
            raise ValueError(
                f"bank_batch_cutoff_time is required on {self.rail.value}: the "
                "presentation-window rule cannot be applied without it"
            )
        return self

    @model_validator(mode="after")
    def notice_precedes_the_charge(self) -> ObservedFailure:
        if self.notified_at > self.original_at:
            raise ValueError("notified_at is after the original attempt it notified")
        return self

    @model_validator(mode="after")
    def history_is_complete_up_to_this_failure(self) -> ObservedFailure:
        """Supplied history must be every attempt before this one, in order.

        A partial history is refused rather than accepted and padded. `BankAware` reads it
        as the whole of what it has observed, so a gap does not read as a gap — it reads
        as a bank that was tried less often than it was, and the tally is wrong with no
        sign that anything is missing.
        """
        if self.attempt_history is None:
            return self
        numbers = [a.attempt_number for a in self.attempt_history]
        if numbers != list(range(1, self.attempt_number)):
            raise ValueError(
                f"attempt_history must hold attempts 1..{self.attempt_number - 1} in "
                f"order, one each; got {numbers or 'none'}"
            )
        if numbers and self.attempt_history[0].scheduled_at != self.original_at:
            raise ValueError("attempt_history[0].scheduled_at disagrees with original_attempt_at")
        return self

    @property
    def original_at(self) -> AwareDatetime:
        """When attempt 1 of this cycle ran. Supplied, or this failure when it is attempt 1."""
        return self.original_attempt_at or self.failed_at

    @property
    def tier(self) -> Tier:
        return (
            Tier.EXTENDED
            if self.bank_id is not None and self.attempt_history is not None
            else Tier.MINIMUM
        )


# The CSV columns, in order. `attempt_history` is absent by construction: a repeated
# per-attempt structure does not fit one row, and a file that flattened it would put the
# merchant in the position of encoding a nested shape by hand.
MINIMUM_COLUMNS: tuple[str, ...] = (
    "mandate_ref",
    "rail",
    "reason_code",
    "failed_at",
    "amount_paise",
    "mandate_cap_paise",
    "attempt_number",
    "notified_at",
    "prior_failure_count",
    "original_attempt_at",
    "bank_batch_cutoff_time",
)

EXTENDED_COLUMNS: tuple[str, ...] = (*MINIMUM_COLUMNS, "bank_id")


def required_columns() -> frozenset[str]:
    """Columns a file must carry whatever its rows say (SPEC §15.1).

    Derived from the model, never listed by hand, so a field added to `ObservedFailure`
    cannot be forgotten by the header check. `original_attempt_at` and
    `bank_batch_cutoff_time` are excluded by construction: they are conditionally required
    *per row*, so their absence is a row-level refusal at the level that knows.
    """
    return frozenset(
        name
        for name, field in ObservedFailure.model_fields.items()
        if field.is_required() and name in EXTENDED_COLUMNS
    )
